### ISSUE TITLE
Magical Monoids

### ISSUE THREAD

**Issue by StackDoesNotWork** [haskellweekly/haskellweekly.github.io#269]
Hello! 

I wrote a new blog post 

Link: https://medium.com/@stackdoesnotwork/magical-monoids-50da92b069f4

Thanks!

**Comment by tfausak** [comment]
Thanks for the suggestion! I'll feature this in today's issue.

As an aside, how would you like to be credited in Haskell Weekly? I typically include author's names on featured articles. I have not been able to find your name connected to your content. Since your handles are inconsistent and somewhat unwieldy, I have no included authorship information on your posts. If that's fine with you I'll keep doing that, or if you have a name you'd like me to use I can do that too.
