### ISSUE TITLE
Job section

### ISSUE THREAD

**Issue by alexeyzab** [haskellweekly/haskellweekly.github.io#57]
Hi there!

I was wondering if it would be a good idea to create an additional section with new Haskell jobs. Something like what This Week in Rust is doing.

If it's a matter of curating the list every week, I can do that. I see the process as something along the lines of checking whoishiring.io, Functional Jobs, Functional Works, AngelList, then posting the relevant links to Haskell jobs. If there aren't any new ones this week, mention that instead.

What do you think?

**Comment by tfausak** [comment]
Hi Alexey! Thanks for the suggestion. I have put job postings in Haskell Weekly before (once, in [issue 23](https://haskellweekly.news/issues/23.html)). I don't really do it anymore for a couple reasons:

- Job postings aren't usually "news" because they can be ongoing for a while. Arguably a new job posting is news, but ...

- Job postings are a potential way to monetize Haskell Weekly. I could write a whole blog post about this, but it suffices to say that I publish Haskell Weekly in my free time using my own money. It would be nice to be able to offset costs, and having companies pay for job listings is one way to do that.

**Comment by alexeyzab** [comment]
That's understandable.

If this situation changes in the future (perhaps if the costs of running Haskell Weekly would be offset by donations?) and you need someone to curate the job postings, let me know, I'd be happy to help.

**Comment by tfausak** [comment]
For sure!

**Comment by tfausak** [comment]
I'm going to close this for now, but I'll keep you in mind if Haskell Weekly ever gets a job section.
